<?php

namespace App\CustomBundle\Repository;

use App\BaseBundle\Repository\BaseRepository;
use App\CustomBundle\Entity\OriginalDesign;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;
use PN\ServiceBundle\Utils\Validate;

/**
 * OriginalDesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OriginalDesignRepository extends BaseRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, OriginalDesign::class, "b");
    }

    protected function getStatement(): QueryBuilder
    {
        return $this->createQueryBuilder('b')
            ->addSelect("-b.tarteb AS HIDDEN inverseTarteb")
            ->addSelect("seo")
            ->addSelect("seoSocials")
            ->addSelect("bTrans")
            ->leftJoin("b.seo", "seo")
            ->leftJoin("seo.seoSocials", "seoSocials")
            ->leftJoin("b.translations", "bTrans");
    }

    private function filterWhereClause(QueryBuilder $statement, \stdClass $search): void
    {
        if (isset($search->string) and Validate::not_null($search->string)) {
            $statement->andWhere('b.id LIKE :searchTerm '
                .'OR b.title LIKE :searchTerm '
            );
            $statement->setParameter('searchTerm', '%'.trim($search->string).'%');
        }


        if (isset($search->publish) and (is_bool($search->publish) or in_array($search->publish, [0, 1]))) {
            $statement->andWhere('b.publish = :publish');
            $statement->setParameter('publish', $search->publish);
        }

        if (isset($search->notId) and $search->notId != "") {
            $statement->andWhere('b.id <> :notId');
            $statement->setParameter('notId', $search->notId);
        }

        if (isset($search->featured) and (is_bool($search->featured) or in_array($search->featured, [0, 1]))) {
            $statement->andWhere('b.featured = :featured');
            $statement->setParameter('featured', $search->featured);
        }

        if (isset($search->deleted) and in_array($search->deleted, [0, 1])) {
            if ($search->deleted == 1) {
                $statement->andWhere('b.deleted IS NOT NULL');
            } else {
                $statement->andWhere('b.deleted IS NULL');
            }
        }
    }

    private function filterOrder(QueryBuilder $statement, \stdClass $search): void
    {
        $sortSQL = [
            'b.id',
            'inverseTarteb',
            'b.title',
            'b.featured',
            'b.created',
        ];

        $this->filterOrderLogic($statement, $search, $sortSQL);
    }


    public function filter($search, $count = false, $startLimit = null, $endLimit = null)
    {
        $statement = $this->getStatement();
        $this->filterWhereClause($statement, $search);

        if ($count) {
            return $this->filterCount($statement);
        }

        $statement->groupBy('b.id');
        $this->filterPagination($statement, $startLimit, $endLimit);
        $this->filterOrder($statement, $search);

        return $statement->getQuery()->execute();
    }


}
