<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230105114459 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE banner (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, sub_title VARCHAR(35) DEFAULT NULL, placement INT NOT NULL, placementName VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, text VARCHAR(255) DEFAULT NULL, action_button_name VARCHAR(20) DEFAULT NULL, action_button_position VARCHAR(255) DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, publish TINYINT(1) NOT NULL, openInNewTab TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_6F9DB8E73DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE banner_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(50) NOT NULL, sub_title VARCHAR(35) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, text VARCHAR(255) DEFAULT NULL, actionButton VARCHAR(20) DEFAULT NULL, INDEX IDX_F8B8D8B2C2AC5D3 (translatable_id), INDEX IDX_F8B8D8B82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, tarteb SMALLINT DEFAULT NULL, date DATETIME DEFAULT NULL, publish TINYINT(1) NOT NULL, featured TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_C015514397E3DD86 (seo_id), UNIQUE INDEX UNIQ_C01551434B89032C (post_id), INDEX IDX_C015514312469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_blog_tag (blog_id INT NOT NULL, blog_tag_id INT NOT NULL, INDEX IDX_72B11DAEDAE07E97 (blog_id), INDEX IDX_72B11DAE2F9DC6D0 (blog_tag_id), PRIMARY KEY(blog_id, blog_tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_category (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, tarteb SMALLINT DEFAULT NULL, publish TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_72113DE697E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_category_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, INDEX IDX_85D2E1FE2C2AC5D3 (translatable_id), INDEX IDX_85D2E1FE82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_tag (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, tarteb SMALLINT DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_6EC398997E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_tag_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, INDEX IDX_12A2DA632C2AC5D3 (translatable_id), INDEX IDX_12A2DA6382F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, subtitle VARCHAR(255) DEFAULT NULL, INDEX IDX_9C6B35002C2AC5D3 (translatable_id), INDEX IDX_9C6B350082F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart (id INT AUTO_INCREMENT NOT NULL, payment_method_id INT DEFAULT NULL, coupon_id INT DEFAULT NULL, shipping_address_id INT DEFAULT NULL, created DATETIME NOT NULL, INDEX IDX_BA388B75AA1164F (payment_method_id), INDEX IDX_BA388B766C5951B (coupon_id), INDEX IDX_BA388B74D4CFF2B (shipping_address_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart_guest_data (cart_id INT NOT NULL, zone_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, address LONGTEXT NOT NULL, mobile_number VARCHAR(20) NOT NULL, INDEX IDX_E923DECC9F2C3FAB (zone_id), PRIMARY KEY(cart_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart_has_cookie (cart_id INT NOT NULL, cookie VARCHAR(255) NOT NULL, PRIMARY KEY(cart_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart_has_product_price (cart_id INT NOT NULL, product_price_id INT NOT NULL, qty INT NOT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, INDEX IDX_D90A9B5C1AD5CDBF (cart_id), INDEX IDX_D90A9B5C1DA4AD70 (product_price_id), PRIMARY KEY(cart_id, product_price_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart_has_user (cart_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_4E50427DA76ED395 (user_id), PRIMARY KEY(cart_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, post_id INT DEFAULT NULL, seo_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, level_one_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, concatIds LONGTEXT DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, depth INT NOT NULL, no_of_images SMALLINT DEFAULT 0, no_of_products SMALLINT DEFAULT 0, no_of_publish_products SMALLINT DEFAULT 0, parentConcatIds LONGTEXT DEFAULT NULL, publish TINYINT(1) NOT NULL, featured TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_64C19C13DA5256D (image_id), UNIQUE INDEX UNIQ_64C19C14B89032C (post_id), UNIQUE INDEX UNIQ_64C19C197E3DD86 (seo_id), INDEX IDX_64C19C1727ACA70 (parent_id), INDEX IDX_64C19C1822CAFB2 (level_one_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_1C60F9152C2AC5D3 (translatable_id), INDEX IDX_1C60F91582F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(45) NOT NULL, price DOUBLE PRECISION NOT NULL, publish TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collection (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, title VARCHAR(45) NOT NULL, publish TINYINT(1) NOT NULL, featured TINYINT(1) NOT NULL, tarteb SMALLINT DEFAULT 0, no_of_products SMALLINT DEFAULT 0, no_of_publish_products SMALLINT DEFAULT 0, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_FC4D653297E3DD86 (seo_id), UNIQUE INDEX UNIQ_FC4D65324B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collection_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_5C94C3AD2C2AC5D3 (translatable_id), INDEX IDX_5C94C3AD82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE coupon (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, comment LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, discount_type VARCHAR(255) NOT NULL, discount_value DOUBLE PRECISION NOT NULL, start_date DATE DEFAULT NULL, expiry_date DATE DEFAULT NULL, minimum_purchase_amount DOUBLE PRECISION DEFAULT NULL, limit_use_per_user INT DEFAULT NULL, total_number_of_use INT DEFAULT NULL, add_discount_after_product_discount TINYINT(1) NOT NULL, free_payment_method_fee TINYINT(1) NOT NULL, first_order_only TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, shipping TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_64BF3F0277153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE coupon_has_product (coupon_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_C3DDFFD166C5951B (coupon_id), INDEX IDX_C3DDFFD14584665A (product_id), PRIMARY KEY(coupon_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE credit_card (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, payment_id INT DEFAULT NULL, token LONGTEXT NOT NULL, masked_pan VARCHAR(45) NOT NULL, card_type VARCHAR(45) NOT NULL, valid TINYINT(1) NOT NULL, created DATETIME NOT NULL, INDEX IDX_11D627EEA76ED395 (user_id), UNIQUE INDEX UNIQ_11D627EE4C3A3BB (payment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(50) NOT NULL, code VARCHAR(3) NOT NULL, symbol VARCHAR(255) NOT NULL, `default` TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_6956883F77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency_translation (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(50) NOT NULL, symbol VARCHAR(255) NOT NULL, INDEX IDX_5814BCE2C2AC5D3 (translatable_id), INDEX IDX_5814BCE82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, base_path VARCHAR(255) DEFAULT NULL, size DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute (id INT AUTO_INCREMENT NOT NULL, dynamic_content_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, value LONGTEXT DEFAULT NULL, type SMALLINT NOT NULL, hint VARCHAR(255) DEFAULT NULL, image_width DOUBLE PRECISION DEFAULT NULL, image_height DOUBLE PRECISION DEFAULT NULL, INDEX IDX_E7247B59D9D0CD7 (dynamic_content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute_image (dynamic_content_attribute_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_697B9E6EF5E49404 (dynamic_content_attribute_id), INDEX IDX_697B9E6E3DA5256D (image_id), PRIMARY KEY(dynamic_content_attribute_id, image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute_document (dynamic_content_attribute_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_E9D18348F5E49404 (dynamic_content_attribute_id), INDEX IDX_E9D18348C33F7837 (document_id), PRIMARY KEY(dynamic_content_attribute_id, document_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, value LONGTEXT DEFAULT NULL, INDEX IDX_A4504A102C2AC5D3 (translatable_id), INDEX IDX_A4504A1082F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_page (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_575ACC497E3DD86 (seo_id), UNIQUE INDEX UNIQ_575ACC44B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_page_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, INDEX IDX_5512AA682C2AC5D3 (translatable_id), INDEX IDX_5512AA6882F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exchange_rate (id INT AUTO_INCREMENT NOT NULL, source_currency_id INT DEFAULT NULL, target_currency_id INT DEFAULT NULL, ratio DOUBLE PRECISION NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, INDEX IDX_E9521FAB45BD1D6 (source_currency_id), INDEX IDX_E9521FABBF1ECE7C (target_currency_id), UNIQUE INDEX exchange_unique (source_currency_id, target_currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(191) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(191) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE faq (id INT AUTO_INCREMENT NOT NULL, question LONGTEXT NOT NULL, answer LONGTEXT NOT NULL, publish TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, question LONGTEXT DEFAULT NULL, answer LONGTEXT DEFAULT NULL, INDEX IDX_99569DA22C2AC5D3 (translatable_id), INDEX IDX_99569DA282F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, base_path VARCHAR(255) DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, size DOUBLE PRECISION DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, image_type SMALLINT DEFAULT NULL, created DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_setting (id INT AUTO_INCREMENT NOT NULL, entity_name VARCHAR(255) DEFAULT NULL, back_route VARCHAR(255) DEFAULT NULL, upload_path VARCHAR(255) DEFAULT NULL, auto_resize TINYINT(1) NOT NULL, quality SMALLINT NOT NULL, gallery TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_A64EF4416EFC72D (entity_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_setting_has_type (image_type_id INT NOT NULL, image_setting_id INT NOT NULL, radio_button TINYINT(1) NOT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, thumb_width DOUBLE PRECISION DEFAULT NULL, thumb_height DOUBLE PRECISION DEFAULT NULL, validate_width_and_height TINYINT(1) NOT NULL, validate_size TINYINT(1) NOT NULL, INDEX IDX_F8AEE740505CDB4F (image_type_id), INDEX IDX_F8AEE74082EBAA44 (image_setting_id), PRIMARY KEY(image_type_id, image_setting_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(5) NOT NULL, title VARCHAR(45) NOT NULL, flag_asset VARCHAR(45) NOT NULL, UNIQUE INDEX UNIQ_D4DB71B54180C698 (locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql('CREATE TABLE occasion (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, title VARCHAR(45) NOT NULL, active TINYINT(1) NOT NULL, publish TINYINT(1) NOT NULL, no_of_products SMALLINT DEFAULT 0, no_of_publish_products SMALLINT DEFAULT 0, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8A66DCE597E3DD86 (seo_id), UNIQUE INDEX UNIQ_8A66DCE54B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE occasion_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_3FAA49AA2C2AC5D3 (translatable_id), INDEX IDX_3FAA49AA82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `order` (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, payment_method_id INT DEFAULT NULL, state VARCHAR(255) NOT NULL, shipping_state VARCHAR(255) NOT NULL, payment_state VARCHAR(255) NOT NULL, success_date DATETIME DEFAULT NULL, item_qty INT DEFAULT NULL, shipping_cost DOUBLE PRECISION NOT NULL, sub_total DOUBLE PRECISION NOT NULL, total_price DOUBLE PRECISION NOT NULL, discount DOUBLE PRECISION DEFAULT NULL, extra_fee DOUBLE PRECISION DEFAULT NULL, cart_id INT DEFAULT NULL, sent_confirmation_email TINYINT(1) NOT NULL, cart LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', cart_product_prices_hash VARCHAR(100) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, uuid VARCHAR(50) NOT NULL, UNIQUE INDEX UNIQ_F5299398D17F50A6 (uuid), INDEX IDX_F5299398A76ED395 (user_id), INDEX IDX_F52993985AA1164F (payment_method_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_comment (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, text LONGTEXT NOT NULL, creator VARCHAR(30) NOT NULL, created DATETIME NOT NULL, INDEX IDX_620EFB278D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_guest_data (order_id INT NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(order_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_has_coupon (order_id INT NOT NULL, coupon_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, discount_type VARCHAR(255) NOT NULL, discount_value DOUBLE PRECISION NOT NULL, start_date DATE DEFAULT NULL, expiry_date DATE DEFAULT NULL, minimum_purchase_amount DOUBLE PRECISION DEFAULT NULL, limit_use_per_user INT DEFAULT NULL, total_number_of_use INT DEFAULT NULL, add_discount_after_product_discount TINYINT(1) NOT NULL, free_payment_method_fee TINYINT(1) NOT NULL, first_order_only TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, shipping TINYINT(1) NOT NULL, INDEX IDX_FB47D5CC66C5951B (coupon_id), PRIMARY KEY(order_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_has_product_price (order_id INT NOT NULL, product_price_id INT NOT NULL, currency_id INT DEFAULT NULL, qty DOUBLE PRECISION NOT NULL, unitPrice DOUBLE PRECISION NOT NULL, total_price DOUBLE PRECISION NOT NULL, stock_withdrawn TINYINT(1) DEFAULT 0 NOT NULL, INDEX IDX_DD0E6FD98D9F6D38 (order_id), INDEX IDX_DD0E6FD91DA4AD70 (product_price_id), INDEX IDX_DD0E6FD938248176 (currency_id), PRIMARY KEY(order_id, product_price_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_log (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, text LONGTEXT NOT NULL, creator VARCHAR(30) NOT NULL, created DATETIME NOT NULL, INDEX IDX_CC6427A58D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_shipping_address (order_id INT NOT NULL, shipping_address_id INT DEFAULT NULL, zone_id INT DEFAULT NULL, title VARCHAR(45) DEFAULT NULL, note LONGTEXT DEFAULT NULL, mobile_number VARCHAR(50) NOT NULL, full_address LONGTEXT DEFAULT NULL, INDEX IDX_89107D594D4CFF2B (shipping_address_id), INDEX IDX_89107D599F2C3FAB (zone_id), PRIMARY KEY(order_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, payment_method_id INT DEFAULT NULL, uuid VARCHAR(50) NOT NULL, type VARCHAR(255) DEFAULT NULL, object_id INT DEFAULT NULL, user_data LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', info LONGTEXT DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, amount_cents DOUBLE PRECISION DEFAULT NULL, txn_message LONGTEXT DEFAULT NULL, txn_response_code VARCHAR(255) DEFAULT NULL, transaction_no VARCHAR(40) DEFAULT NULL, sent_data LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', received_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', credit_card_received_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', gateway VARCHAR(255) DEFAULT NULL, is_automated TINYINT(1) NOT NULL, is_success TINYINT(1) NOT NULL, is_refunded TINYINT(1) NOT NULL, created DATETIME NOT NULL, UNIQUE INDEX UNIQ_6D28840DD17F50A6 (uuid), INDEX IDX_6D28840D5AA1164F (payment_method_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_method (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, title VARCHAR(45) NOT NULL, note LONGTEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, fees DOUBLE PRECISION DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_7B61A1F68CDE5729 (type), UNIQUE INDEX UNIQ_7B61A1F63DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_method_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, note LONGTEXT DEFAULT NULL, INDEX IDX_5A37F1802C2AC5D3 (translatable_id), INDEX IDX_5A37F18082F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_image (post_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_522688B04B89032C (post_id), INDEX IDX_522688B03DA5256D (image_id), PRIMARY KEY(post_id, image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, content LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_6D8AA7542C2AC5D3 (translatable_id), INDEX IDX_6D8AA75482F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, category_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, main_image_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, sku VARCHAR(100) DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, search_terms LONGTEXT DEFAULT NULL, normalized_text LONGTEXT DEFAULT NULL, featured TINYINT(1) NOT NULL, new_arrival TINYINT(1) NOT NULL, enable_variants TINYINT(1) NOT NULL, publish TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, uuid VARCHAR(50) NOT NULL, UNIQUE INDEX UNIQ_D34A04ADD17F50A6 (uuid), UNIQUE INDEX UNIQ_D34A04AD97E3DD86 (seo_id), UNIQUE INDEX UNIQ_D34A04AD4B89032C (post_id), INDEX IDX_D34A04AD12469DE2 (category_id), INDEX IDX_D34A04AD38248176 (currency_id), INDEX IDX_D34A04ADE4873418 (main_image_id), FULLTEXT INDEX IDX_D34A04ADB334D8E9 (normalized_text), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_attribute (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, type VARCHAR(45) NOT NULL, tarteb SMALLINT DEFAULT NULL, search TINYINT(1) NOT NULL, mandatory TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, INDEX IDX_94DA597612469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_attribute_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_29FE3462C2AC5D3 (translatable_id), INDEX IDX_29FE34682F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_collection (collection_id INT NOT NULL, product_id INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_6F2A3A19514956FD (collection_id), INDEX IDX_6F2A3A194584665A (product_id), PRIMARY KEY(collection_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_details (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, augmented_reality_url LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_A3FF103A4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_has_related_product (product_id INT NOT NULL, related_product_id INT NOT NULL, INDEX IDX_A3E02CB34584665A (product_id), INDEX IDX_A3E02CB3CF496EEA (related_product_id), PRIMARY KEY(product_id, related_product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_favorite (user_id INT NOT NULL, product_id INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_A375E44EA76ED395 (user_id), INDEX IDX_A375E44E4584665A (product_id), PRIMARY KEY(user_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_has_attribute (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, attribute_id INT DEFAULT NULL, sub_attribute_id INT DEFAULT NULL, other_value VARCHAR(255) DEFAULT NULL, INDEX IDX_13261464584665A (product_id), INDEX IDX_1326146B6E62EFA (attribute_id), INDEX IDX_1326146A1B469CC (sub_attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_occasion (occasion_id INT NOT NULL, product_id INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_41D6B6724034998F (occasion_id), INDEX IDX_41D6B6724584665A (product_id), PRIMARY KEY(occasion_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_price (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, title VARCHAR(150) DEFAULT NULL, stock INT DEFAULT 0, unit_price DOUBLE PRECISION NOT NULL, promotional_price DOUBLE PRECISION DEFAULT NULL, promotional_expiry_date DATE DEFAULT NULL, variant_option_ids LONGTEXT DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, INDEX IDX_6B9459854584665A (product_id), INDEX IDX_6B94598538248176 (currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_price_has_variant_option (product_price_id INT NOT NULL, variant_id INT NOT NULL, option_id INT NOT NULL, INDEX IDX_4253E681DA4AD70 (product_price_id), INDEX IDX_4253E683B69A9AF (variant_id), INDEX IDX_4253E68A7C41D6F (option_id), PRIMARY KEY(product_price_id, variant_id, option_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_search (product_id INT NOT NULL, product_price_id INT DEFAULT NULL, category_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, main_image_id INT DEFAULT NULL, titles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', slugs LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', specs LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', min_sell_price DOUBLE PRECISION NOT NULL, max_sell_price DOUBLE PRECISION NOT NULL, min_original_price DOUBLE PRECISION NOT NULL, max_original_price DOUBLE PRECISION NOT NULL, normalized_text LONGTEXT DEFAULT NULL, has_multi_price TINYINT(1) NOT NULL, featured TINYINT(1) NOT NULL, recommended_sort SMALLINT NOT NULL, new_arrival TINYINT(1) NOT NULL, has_offer TINYINT(1) NOT NULL, offer_expiry_date DATE DEFAULT NULL, promotion_percentage DOUBLE PRECISION DEFAULT NULL, has_stock TINYINT(1) DEFAULT 1 NOT NULL, last_update_datetime DATETIME NOT NULL, INDEX IDX_D68C9A031DA4AD70 (product_price_id), INDEX IDX_D68C9A0312469DE2 (category_id), INDEX IDX_D68C9A0338248176 (currency_id), INDEX IDX_D68C9A03E4873418 (main_image_id), FULLTEXT INDEX IDX_D68C9A03B334D8E9 (normalized_text), PRIMARY KEY(product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_sub_attribute (id INT AUTO_INCREMENT NOT NULL, attribute_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, INDEX IDX_329AB5B7B6E62EFA (attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_sub_attribute_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_FD7FA36F2C2AC5D3 (translatable_id), INDEX IDX_FD7FA36F82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, INDEX IDX_4B13F8EC2C2AC5D3 (translatable_id), INDEX IDX_4B13F8EC82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_variant (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, tarteb SMALLINT DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, INDEX IDX_209AA41D4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_variant_option (id INT AUTO_INCREMENT NOT NULL, variant_id INT DEFAULT NULL, image_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, INDEX IDX_1CB5D94A3B69A9AF (variant_id), UNIQUE INDEX UNIQ_1CB5D94A3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_variant_option_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, INDEX IDX_C965F3792C2AC5D3 (translatable_id), INDEX IDX_C965F37982F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_variant_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, INDEX IDX_60D25BED2C2AC5D3 (translatable_id), INDEX IDX_60D25BED82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project (id INT AUTO_INCREMENT NOT NULL, post_id INT DEFAULT NULL, seo_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, tarteb SMALLINT DEFAULT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', featured TINYINT(1) NOT NULL, publish TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_2FB3D0EE4B89032C (post_id), UNIQUE INDEX UNIQ_2FB3D0EE97E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_product (project_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_455408C8166D1F9C (project_id), INDEX IDX_455408C84584665A (product_id), PRIMARY KEY(project_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, INDEX IDX_EC103EE42C2AC5D3 (translatable_id), INDEX IDX_EC103EE482F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redirect_404 (id INT AUTO_INCREMENT NOT NULL, `from` LONGTEXT NOT NULL, `to` LONGTEXT NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_keyword (id INT AUTO_INCREMENT NOT NULL, keyword VARCHAR(150) NOT NULL, canonical_keyword VARCHAR(150) NOT NULL, ip VARCHAR(50) NOT NULL, created DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo (id INT AUTO_INCREMENT NOT NULL, seo_base_route_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, meta_description LONGTEXT DEFAULT NULL, focus_keyword VARCHAR(255) DEFAULT NULL, meta_keyword VARCHAR(255) DEFAULT NULL, meta_tags LONGTEXT DEFAULT NULL, state SMALLINT DEFAULT NULL, last_modified DATETIME NOT NULL, deleted TINYINT(1) DEFAULT 0 NOT NULL, INDEX IDX_6C71EC30AB839C52 (seo_base_route_id), UNIQUE INDEX slug_unique (slug, seo_base_route_id, deleted), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_seo_social (seo_id INT NOT NULL, seo_social_id INT NOT NULL, INDEX IDX_F296CD9297E3DD86 (seo_id), INDEX IDX_F296CD922A6ABD62 (seo_social_id), PRIMARY KEY(seo_id, seo_social_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_base_route (id INT AUTO_INCREMENT NOT NULL, entity_name VARCHAR(255) NOT NULL, base_route VARCHAR(255) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_B98C855216EFC72D (entity_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_page (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, brief LONGTEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_E8DCA6F18CDE5729 (type), UNIQUE INDEX UNIQ_E8DCA6F197E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_page_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, brief LONGTEXT DEFAULT NULL, INDEX IDX_ED5F1E392C2AC5D3 (translatable_id), INDEX IDX_ED5F1E3982F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_social (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, social_network SMALLINT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_social_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, INDEX IDX_4DC1EE9B2C2AC5D3 (translatable_id), INDEX IDX_4DC1EE9B82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, meta_description LONGTEXT DEFAULT NULL, focus_keyword VARCHAR(255) DEFAULT NULL, meta_keyword VARCHAR(255) DEFAULT NULL, meta_tags LONGTEXT DEFAULT NULL, state SMALLINT DEFAULT NULL, INDEX IDX_227D72A52C2AC5D3 (translatable_id), INDEX IDX_227D72A582F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, post_id INT DEFAULT NULL, seo_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, publish TINYINT(1) NOT NULL, contact_text TEXT DEFAULT NULL, tarteb INT NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_E19D9AD24B89032C (post_id), UNIQUE INDEX UNIQ_E19D9AD297E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, contact_text TEXT DEFAULT NULL, INDEX IDX_191BAF622C2AC5D3 (translatable_id), INDEX IDX_191BAF6282F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shipping_address (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, zone_id INT DEFAULT NULL, `default` TINYINT(1) NOT NULL, title VARCHAR(45) DEFAULT NULL, note LONGTEXT DEFAULT NULL, mobile_number VARCHAR(50) NOT NULL, full_address LONGTEXT DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, INDEX IDX_EB066945A76ED395 (user_id), INDEX IDX_EB0669459F2C3FAB (zone_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE site_setting (id INT AUTO_INCREMENT NOT NULL, constant_name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, manage_by_super_admin_only TINYINT(1) NOT NULL, value LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_64D05A53C647335D (constant_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, position VARCHAR(100) NOT NULL, tarteb SMALLINT DEFAULT NULL, publish TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_C4E0A61F3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, position VARCHAR(255) DEFAULT NULL, INDEX IDX_CE31D7452C2AC5D3 (translatable_id), INDEX IDX_CE31D74582F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE testimonial (id INT AUTO_INCREMENT NOT NULL, client VARCHAR(255) NOT NULL, position VARCHAR(255) DEFAULT NULL, message LONGTEXT NOT NULL, publish TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE testimonial_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, client VARCHAR(255) DEFAULT NULL, position VARCHAR(255) DEFAULT NULL, message TINYTEXT DEFAULT NULL, INDEX IDX_9BE970A92C2AC5D3 (translatable_id), INDEX IDX_9BE970A982F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, full_name VARCHAR(255) NOT NULL, gender VARCHAR(20) DEFAULT NULL, birthdate DATETIME DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, facebook_id VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, cart_item_no INT DEFAULT NULL, success_order_no INT DEFAULT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, last_login DATETIME DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', confirmation_token VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(255) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(255) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D649A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE banner ADD CONSTRAINT FK_6F9DB8E73DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE banner_translations ADD CONSTRAINT FK_F8B8D8B2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES banner (id)');
        $this->addSql('ALTER TABLE banner_translations ADD CONSTRAINT FK_F8B8D8B82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE blog ADD CONSTRAINT FK_C015514397E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE blog ADD CONSTRAINT FK_C01551434B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE blog ADD CONSTRAINT FK_C015514312469DE2 FOREIGN KEY (category_id) REFERENCES blog_category (id)');
        $this->addSql('ALTER TABLE blog_blog_tag ADD CONSTRAINT FK_72B11DAEDAE07E97 FOREIGN KEY (blog_id) REFERENCES blog (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_blog_tag ADD CONSTRAINT FK_72B11DAE2F9DC6D0 FOREIGN KEY (blog_tag_id) REFERENCES blog_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_category ADD CONSTRAINT FK_72113DE697E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE blog_category_translations ADD CONSTRAINT FK_85D2E1FE2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES blog_category (id)');
        $this->addSql('ALTER TABLE blog_category_translations ADD CONSTRAINT FK_85D2E1FE82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE blog_tag ADD CONSTRAINT FK_6EC398997E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE blog_tag_translations ADD CONSTRAINT FK_12A2DA632C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES blog_tag (id)');
        $this->addSql('ALTER TABLE blog_tag_translations ADD CONSTRAINT FK_12A2DA6382F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE blog_translations ADD CONSTRAINT FK_9C6B35002C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES blog (id)');
        $this->addSql('ALTER TABLE blog_translations ADD CONSTRAINT FK_9C6B350082F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B75AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_method (id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B766C5951B FOREIGN KEY (coupon_id) REFERENCES coupon (id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B74D4CFF2B FOREIGN KEY (shipping_address_id) REFERENCES shipping_address (id)');
        $this->addSql('ALTER TABLE cart_guest_data ADD CONSTRAINT FK_E923DECC1AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_guest_data ADD CONSTRAINT FK_E923DECC9F2C3FAB FOREIGN KEY (zone_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE cart_has_cookie ADD CONSTRAINT FK_C6A8DD0F1AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_has_product_price ADD CONSTRAINT FK_D90A9B5C1AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_has_product_price ADD CONSTRAINT FK_D90A9B5C1DA4AD70 FOREIGN KEY (product_price_id) REFERENCES product_price (id)');
        $this->addSql('ALTER TABLE cart_has_user ADD CONSTRAINT FK_4E50427D1AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_has_user ADD CONSTRAINT FK_4E50427DA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C13DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C14B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C197E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1822CAFB2 FOREIGN KEY (level_one_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE category_translations ADD CONSTRAINT FK_1C60F9152C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE category_translations ADD CONSTRAINT FK_1C60F91582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D653297E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D65324B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE collection_translations ADD CONSTRAINT FK_5C94C3AD2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES collection (id)');
        $this->addSql('ALTER TABLE collection_translations ADD CONSTRAINT FK_5C94C3AD82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE coupon_has_product ADD CONSTRAINT FK_C3DDFFD166C5951B FOREIGN KEY (coupon_id) REFERENCES coupon (id)');
        $this->addSql('ALTER TABLE coupon_has_product ADD CONSTRAINT FK_C3DDFFD14584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE credit_card ADD CONSTRAINT FK_11D627EEA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE credit_card ADD CONSTRAINT FK_11D627EE4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id)');
        $this->addSql('ALTER TABLE currency_translation ADD CONSTRAINT FK_5814BCE2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE currency_translation ADD CONSTRAINT FK_5814BCE82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE dynamic_content_attribute ADD CONSTRAINT FK_E7247B59D9D0CD7 FOREIGN KEY (dynamic_content_id) REFERENCES dynamic_content (id)');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image ADD CONSTRAINT FK_697B9E6EF5E49404 FOREIGN KEY (dynamic_content_attribute_id) REFERENCES dynamic_content_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image ADD CONSTRAINT FK_697B9E6E3DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document ADD CONSTRAINT FK_E9D18348F5E49404 FOREIGN KEY (dynamic_content_attribute_id) REFERENCES dynamic_content_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document ADD CONSTRAINT FK_E9D18348C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations ADD CONSTRAINT FK_A4504A102C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES dynamic_content_attribute (id)');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations ADD CONSTRAINT FK_A4504A1082F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE dynamic_page ADD CONSTRAINT FK_575ACC497E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE dynamic_page ADD CONSTRAINT FK_575ACC44B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE dynamic_page_translations ADD CONSTRAINT FK_5512AA682C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES dynamic_page (id)');
        $this->addSql('ALTER TABLE dynamic_page_translations ADD CONSTRAINT FK_5512AA6882F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FAB45BD1D6 FOREIGN KEY (source_currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FABBF1ECE7C FOREIGN KEY (target_currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE faq_translations ADD CONSTRAINT FK_99569DA22C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES faq (id)');
        $this->addSql('ALTER TABLE faq_translations ADD CONSTRAINT FK_99569DA282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE image_setting_has_type ADD CONSTRAINT FK_F8AEE740505CDB4F FOREIGN KEY (image_type_id) REFERENCES image_type (id)');
        $this->addSql('ALTER TABLE image_setting_has_type ADD CONSTRAINT FK_F8AEE74082EBAA44 FOREIGN KEY (image_setting_id) REFERENCES image_setting (id)');

        $this->addSql('ALTER TABLE occasion ADD CONSTRAINT FK_8A66DCE597E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE occasion ADD CONSTRAINT FK_8A66DCE54B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE occasion_translations ADD CONSTRAINT FK_3FAA49AA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES occasion (id)');
        $this->addSql('ALTER TABLE occasion_translations ADD CONSTRAINT FK_3FAA49AA82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993985AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_method (id)');
        $this->addSql('ALTER TABLE order_comment ADD CONSTRAINT FK_620EFB278D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_guest_data ADD CONSTRAINT FK_3A93536B8D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_has_coupon ADD CONSTRAINT FK_FB47D5CC8D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_has_coupon ADD CONSTRAINT FK_FB47D5CC66C5951B FOREIGN KEY (coupon_id) REFERENCES coupon (id)');
        $this->addSql('ALTER TABLE order_has_product_price ADD CONSTRAINT FK_DD0E6FD98D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_has_product_price ADD CONSTRAINT FK_DD0E6FD91DA4AD70 FOREIGN KEY (product_price_id) REFERENCES product_price (id)');
        $this->addSql('ALTER TABLE order_has_product_price ADD CONSTRAINT FK_DD0E6FD938248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE order_log ADD CONSTRAINT FK_CC6427A58D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_shipping_address ADD CONSTRAINT FK_89107D598D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE order_shipping_address ADD CONSTRAINT FK_89107D594D4CFF2B FOREIGN KEY (shipping_address_id) REFERENCES shipping_address (id)');
        $this->addSql('ALTER TABLE order_shipping_address ADD CONSTRAINT FK_89107D599F2C3FAB FOREIGN KEY (zone_id) REFERENCES city (id)');

        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D5AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_method (id)');
        $this->addSql('ALTER TABLE payment_method ADD CONSTRAINT FK_7B61A1F63DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE payment_method_translations ADD CONSTRAINT FK_5A37F1802C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES payment_method (id)');
        $this->addSql('ALTER TABLE payment_method_translations ADD CONSTRAINT FK_5A37F18082F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE post_image ADD CONSTRAINT FK_522688B04B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_image ADD CONSTRAINT FK_522688B03DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_translations ADD CONSTRAINT FK_6D8AA7542C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE post_translations ADD CONSTRAINT FK_6D8AA75482F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD97E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD4B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD38248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADE4873418 FOREIGN KEY (main_image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA597612469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE product_attribute_translations ADD CONSTRAINT FK_29FE3462C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product_attribute (id)');
        $this->addSql('ALTER TABLE product_attribute_translations ADD CONSTRAINT FK_29FE34682F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product_collection ADD CONSTRAINT FK_6F2A3A19514956FD FOREIGN KEY (collection_id) REFERENCES collection (id)');
        $this->addSql('ALTER TABLE product_collection ADD CONSTRAINT FK_6F2A3A194584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_details ADD CONSTRAINT FK_A3FF103A4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_has_related_product ADD CONSTRAINT FK_A3E02CB34584665A FOREIGN KEY (product_id) REFERENCES product_details (id)');
        $this->addSql('ALTER TABLE product_has_related_product ADD CONSTRAINT FK_A3E02CB3CF496EEA FOREIGN KEY (related_product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_favorite ADD CONSTRAINT FK_A375E44EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE product_favorite ADD CONSTRAINT FK_A375E44E4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_has_attribute ADD CONSTRAINT FK_13261464584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_has_attribute ADD CONSTRAINT FK_1326146B6E62EFA FOREIGN KEY (attribute_id) REFERENCES product_attribute (id)');
        $this->addSql('ALTER TABLE product_has_attribute ADD CONSTRAINT FK_1326146A1B469CC FOREIGN KEY (sub_attribute_id) REFERENCES product_sub_attribute (id)');
        $this->addSql('ALTER TABLE product_occasion ADD CONSTRAINT FK_41D6B6724034998F FOREIGN KEY (occasion_id) REFERENCES occasion (id)');
        $this->addSql('ALTER TABLE product_occasion ADD CONSTRAINT FK_41D6B6724584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B9459854584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B94598538248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE product_price_has_variant_option ADD CONSTRAINT FK_4253E681DA4AD70 FOREIGN KEY (product_price_id) REFERENCES product_price (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_price_has_variant_option ADD CONSTRAINT FK_4253E683B69A9AF FOREIGN KEY (variant_id) REFERENCES product_variant (id)');
        $this->addSql('ALTER TABLE product_price_has_variant_option ADD CONSTRAINT FK_4253E68A7C41D6F FOREIGN KEY (option_id) REFERENCES product_variant_option (id)');
        $this->addSql('ALTER TABLE product_search ADD CONSTRAINT FK_D68C9A034584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_search ADD CONSTRAINT FK_D68C9A031DA4AD70 FOREIGN KEY (product_price_id) REFERENCES product_price (id)');
        $this->addSql('ALTER TABLE product_search ADD CONSTRAINT FK_D68C9A0312469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE product_search ADD CONSTRAINT FK_D68C9A0338248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE product_search ADD CONSTRAINT FK_D68C9A03E4873418 FOREIGN KEY (main_image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE product_sub_attribute ADD CONSTRAINT FK_329AB5B7B6E62EFA FOREIGN KEY (attribute_id) REFERENCES product_attribute (id)');
        $this->addSql('ALTER TABLE product_sub_attribute_translations ADD CONSTRAINT FK_FD7FA36F2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product_sub_attribute (id)');
        $this->addSql('ALTER TABLE product_sub_attribute_translations ADD CONSTRAINT FK_FD7FA36F82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product_translations ADD CONSTRAINT FK_4B13F8EC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_translations ADD CONSTRAINT FK_4B13F8EC82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product_variant ADD CONSTRAINT FK_209AA41D4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_variant_option ADD CONSTRAINT FK_1CB5D94A3B69A9AF FOREIGN KEY (variant_id) REFERENCES product_variant (id)');
        $this->addSql('ALTER TABLE product_variant_option ADD CONSTRAINT FK_1CB5D94A3DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE product_variant_option_translations ADD CONSTRAINT FK_C965F3792C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product_variant_option (id)');
        $this->addSql('ALTER TABLE product_variant_option_translations ADD CONSTRAINT FK_C965F37982F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product_variant_translations ADD CONSTRAINT FK_60D25BED2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product_variant (id)');
        $this->addSql('ALTER TABLE product_variant_translations ADD CONSTRAINT FK_60D25BED82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE4B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE97E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE project_product ADD CONSTRAINT FK_455408C8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_product ADD CONSTRAINT FK_455408C84584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_translations ADD CONSTRAINT FK_EC103EE42C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_translations ADD CONSTRAINT FK_EC103EE482F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE seo ADD CONSTRAINT FK_6C71EC30AB839C52 FOREIGN KEY (seo_base_route_id) REFERENCES seo_base_route (id)');
        $this->addSql('ALTER TABLE seo_seo_social ADD CONSTRAINT FK_F296CD9297E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seo_seo_social ADD CONSTRAINT FK_F296CD922A6ABD62 FOREIGN KEY (seo_social_id) REFERENCES seo_social (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seo_page ADD CONSTRAINT FK_E8DCA6F197E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE seo_page_translations ADD CONSTRAINT FK_ED5F1E392C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES seo_page (id)');
        $this->addSql('ALTER TABLE seo_page_translations ADD CONSTRAINT FK_ED5F1E3982F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE seo_social_translations ADD CONSTRAINT FK_4DC1EE9B2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES seo_social (id)');
        $this->addSql('ALTER TABLE seo_social_translations ADD CONSTRAINT FK_4DC1EE9B82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE seo_translations ADD CONSTRAINT FK_227D72A52C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE seo_translations ADD CONSTRAINT FK_227D72A582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD24B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD297E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE service_translations ADD CONSTRAINT FK_191BAF622C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE service_translations ADD CONSTRAINT FK_191BAF6282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE shipping_address ADD CONSTRAINT FK_EB066945A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE shipping_address ADD CONSTRAINT FK_EB0669459F2C3FAB FOREIGN KEY (zone_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F3DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE team_translations ADD CONSTRAINT FK_CE31D7452C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE team_translations ADD CONSTRAINT FK_CE31D74582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE testimonial_translations ADD CONSTRAINT FK_9BE970A92C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES testimonial (id)');
        $this->addSql('ALTER TABLE testimonial_translations ADD CONSTRAINT FK_9BE970A982F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE banner DROP FOREIGN KEY FK_6F9DB8E73DA5256D');
        $this->addSql('ALTER TABLE banner_translations DROP FOREIGN KEY FK_F8B8D8B2C2AC5D3');
        $this->addSql('ALTER TABLE banner_translations DROP FOREIGN KEY FK_F8B8D8B82F1BAF4');
        $this->addSql('ALTER TABLE blog DROP FOREIGN KEY FK_C015514397E3DD86');
        $this->addSql('ALTER TABLE blog DROP FOREIGN KEY FK_C01551434B89032C');
        $this->addSql('ALTER TABLE blog DROP FOREIGN KEY FK_C015514312469DE2');
        $this->addSql('ALTER TABLE blog_blog_tag DROP FOREIGN KEY FK_72B11DAEDAE07E97');
        $this->addSql('ALTER TABLE blog_blog_tag DROP FOREIGN KEY FK_72B11DAE2F9DC6D0');
        $this->addSql('ALTER TABLE blog_category DROP FOREIGN KEY FK_72113DE697E3DD86');
        $this->addSql('ALTER TABLE blog_category_translations DROP FOREIGN KEY FK_85D2E1FE2C2AC5D3');
        $this->addSql('ALTER TABLE blog_category_translations DROP FOREIGN KEY FK_85D2E1FE82F1BAF4');
        $this->addSql('ALTER TABLE blog_tag DROP FOREIGN KEY FK_6EC398997E3DD86');
        $this->addSql('ALTER TABLE blog_tag_translations DROP FOREIGN KEY FK_12A2DA632C2AC5D3');
        $this->addSql('ALTER TABLE blog_tag_translations DROP FOREIGN KEY FK_12A2DA6382F1BAF4');
        $this->addSql('ALTER TABLE blog_translations DROP FOREIGN KEY FK_9C6B35002C2AC5D3');
        $this->addSql('ALTER TABLE blog_translations DROP FOREIGN KEY FK_9C6B350082F1BAF4');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B75AA1164F');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B766C5951B');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B74D4CFF2B');
        $this->addSql('ALTER TABLE cart_guest_data DROP FOREIGN KEY FK_E923DECC1AD5CDBF');
        $this->addSql('ALTER TABLE cart_guest_data DROP FOREIGN KEY FK_E923DECC9F2C3FAB');
        $this->addSql('ALTER TABLE cart_has_cookie DROP FOREIGN KEY FK_C6A8DD0F1AD5CDBF');
        $this->addSql('ALTER TABLE cart_has_product_price DROP FOREIGN KEY FK_D90A9B5C1AD5CDBF');
        $this->addSql('ALTER TABLE cart_has_product_price DROP FOREIGN KEY FK_D90A9B5C1DA4AD70');
        $this->addSql('ALTER TABLE cart_has_user DROP FOREIGN KEY FK_4E50427D1AD5CDBF');
        $this->addSql('ALTER TABLE cart_has_user DROP FOREIGN KEY FK_4E50427DA76ED395');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C13DA5256D');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C14B89032C');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C197E3DD86');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1727ACA70');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1822CAFB2');
        $this->addSql('ALTER TABLE category_translations DROP FOREIGN KEY FK_1C60F9152C2AC5D3');
        $this->addSql('ALTER TABLE category_translations DROP FOREIGN KEY FK_1C60F91582F1BAF4');
        $this->addSql('ALTER TABLE collection DROP FOREIGN KEY FK_FC4D653297E3DD86');
        $this->addSql('ALTER TABLE collection DROP FOREIGN KEY FK_FC4D65324B89032C');
        $this->addSql('ALTER TABLE collection_translations DROP FOREIGN KEY FK_5C94C3AD2C2AC5D3');
        $this->addSql('ALTER TABLE collection_translations DROP FOREIGN KEY FK_5C94C3AD82F1BAF4');
        $this->addSql('ALTER TABLE coupon_has_product DROP FOREIGN KEY FK_C3DDFFD166C5951B');
        $this->addSql('ALTER TABLE coupon_has_product DROP FOREIGN KEY FK_C3DDFFD14584665A');
        $this->addSql('ALTER TABLE credit_card DROP FOREIGN KEY FK_11D627EEA76ED395');
        $this->addSql('ALTER TABLE credit_card DROP FOREIGN KEY FK_11D627EE4C3A3BB');
        $this->addSql('ALTER TABLE currency_translation DROP FOREIGN KEY FK_5814BCE2C2AC5D3');
        $this->addSql('ALTER TABLE currency_translation DROP FOREIGN KEY FK_5814BCE82F1BAF4');
        $this->addSql('ALTER TABLE dynamic_content_attribute DROP FOREIGN KEY FK_E7247B59D9D0CD7');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image DROP FOREIGN KEY FK_697B9E6EF5E49404');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image DROP FOREIGN KEY FK_697B9E6E3DA5256D');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document DROP FOREIGN KEY FK_E9D18348F5E49404');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document DROP FOREIGN KEY FK_E9D18348C33F7837');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations DROP FOREIGN KEY FK_A4504A102C2AC5D3');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations DROP FOREIGN KEY FK_A4504A1082F1BAF4');
        $this->addSql('ALTER TABLE dynamic_page DROP FOREIGN KEY FK_575ACC497E3DD86');
        $this->addSql('ALTER TABLE dynamic_page DROP FOREIGN KEY FK_575ACC44B89032C');
        $this->addSql('ALTER TABLE dynamic_page_translations DROP FOREIGN KEY FK_5512AA682C2AC5D3');
        $this->addSql('ALTER TABLE dynamic_page_translations DROP FOREIGN KEY FK_5512AA6882F1BAF4');
        $this->addSql('ALTER TABLE exchange_rate DROP FOREIGN KEY FK_E9521FAB45BD1D6');
        $this->addSql('ALTER TABLE exchange_rate DROP FOREIGN KEY FK_E9521FABBF1ECE7C');
        $this->addSql('ALTER TABLE faq_translations DROP FOREIGN KEY FK_99569DA22C2AC5D3');
        $this->addSql('ALTER TABLE faq_translations DROP FOREIGN KEY FK_99569DA282F1BAF4');
        $this->addSql('ALTER TABLE image_setting_has_type DROP FOREIGN KEY FK_F8AEE740505CDB4F');
        $this->addSql('ALTER TABLE image_setting_has_type DROP FOREIGN KEY FK_F8AEE74082EBAA44');

        $this->addSql('ALTER TABLE occasion DROP FOREIGN KEY FK_8A66DCE597E3DD86');
        $this->addSql('ALTER TABLE occasion DROP FOREIGN KEY FK_8A66DCE54B89032C');
        $this->addSql('ALTER TABLE occasion_translations DROP FOREIGN KEY FK_3FAA49AA2C2AC5D3');
        $this->addSql('ALTER TABLE occasion_translations DROP FOREIGN KEY FK_3FAA49AA82F1BAF4');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993985AA1164F');
        $this->addSql('ALTER TABLE order_comment DROP FOREIGN KEY FK_620EFB278D9F6D38');
        $this->addSql('ALTER TABLE order_guest_data DROP FOREIGN KEY FK_3A93536B8D9F6D38');
        $this->addSql('ALTER TABLE order_has_coupon DROP FOREIGN KEY FK_FB47D5CC8D9F6D38');
        $this->addSql('ALTER TABLE order_has_coupon DROP FOREIGN KEY FK_FB47D5CC66C5951B');
        $this->addSql('ALTER TABLE order_has_product_price DROP FOREIGN KEY FK_DD0E6FD98D9F6D38');
        $this->addSql('ALTER TABLE order_has_product_price DROP FOREIGN KEY FK_DD0E6FD91DA4AD70');
        $this->addSql('ALTER TABLE order_has_product_price DROP FOREIGN KEY FK_DD0E6FD938248176');
        $this->addSql('ALTER TABLE order_log DROP FOREIGN KEY FK_CC6427A58D9F6D38');
        $this->addSql('ALTER TABLE order_shipping_address DROP FOREIGN KEY FK_89107D598D9F6D38');
        $this->addSql('ALTER TABLE order_shipping_address DROP FOREIGN KEY FK_89107D594D4CFF2B');
        $this->addSql('ALTER TABLE order_shipping_address DROP FOREIGN KEY FK_89107D599F2C3FAB');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D5AA1164F');
        $this->addSql('ALTER TABLE payment_method DROP FOREIGN KEY FK_7B61A1F63DA5256D');
        $this->addSql('ALTER TABLE payment_method_translations DROP FOREIGN KEY FK_5A37F1802C2AC5D3');
        $this->addSql('ALTER TABLE payment_method_translations DROP FOREIGN KEY FK_5A37F18082F1BAF4');
        $this->addSql('ALTER TABLE post_image DROP FOREIGN KEY FK_522688B04B89032C');
        $this->addSql('ALTER TABLE post_image DROP FOREIGN KEY FK_522688B03DA5256D');
        $this->addSql('ALTER TABLE post_translations DROP FOREIGN KEY FK_6D8AA7542C2AC5D3');
        $this->addSql('ALTER TABLE post_translations DROP FOREIGN KEY FK_6D8AA75482F1BAF4');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD97E3DD86');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD4B89032C');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD38248176');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADE4873418');
        $this->addSql('ALTER TABLE product_attribute DROP FOREIGN KEY FK_94DA597612469DE2');
        $this->addSql('ALTER TABLE product_attribute_translations DROP FOREIGN KEY FK_29FE3462C2AC5D3');
        $this->addSql('ALTER TABLE product_attribute_translations DROP FOREIGN KEY FK_29FE34682F1BAF4');
        $this->addSql('ALTER TABLE product_collection DROP FOREIGN KEY FK_6F2A3A19514956FD');
        $this->addSql('ALTER TABLE product_collection DROP FOREIGN KEY FK_6F2A3A194584665A');
        $this->addSql('ALTER TABLE product_details DROP FOREIGN KEY FK_A3FF103A4584665A');
        $this->addSql('ALTER TABLE product_has_related_product DROP FOREIGN KEY FK_A3E02CB34584665A');
        $this->addSql('ALTER TABLE product_has_related_product DROP FOREIGN KEY FK_A3E02CB3CF496EEA');
        $this->addSql('ALTER TABLE product_favorite DROP FOREIGN KEY FK_A375E44EA76ED395');
        $this->addSql('ALTER TABLE product_favorite DROP FOREIGN KEY FK_A375E44E4584665A');
        $this->addSql('ALTER TABLE product_has_attribute DROP FOREIGN KEY FK_13261464584665A');
        $this->addSql('ALTER TABLE product_has_attribute DROP FOREIGN KEY FK_1326146B6E62EFA');
        $this->addSql('ALTER TABLE product_has_attribute DROP FOREIGN KEY FK_1326146A1B469CC');
        $this->addSql('ALTER TABLE product_occasion DROP FOREIGN KEY FK_41D6B6724034998F');
        $this->addSql('ALTER TABLE product_occasion DROP FOREIGN KEY FK_41D6B6724584665A');
        $this->addSql('ALTER TABLE product_price DROP FOREIGN KEY FK_6B9459854584665A');
        $this->addSql('ALTER TABLE product_price DROP FOREIGN KEY FK_6B94598538248176');
        $this->addSql('ALTER TABLE product_price_has_variant_option DROP FOREIGN KEY FK_4253E681DA4AD70');
        $this->addSql('ALTER TABLE product_price_has_variant_option DROP FOREIGN KEY FK_4253E683B69A9AF');
        $this->addSql('ALTER TABLE product_price_has_variant_option DROP FOREIGN KEY FK_4253E68A7C41D6F');
        $this->addSql('ALTER TABLE product_search DROP FOREIGN KEY FK_D68C9A034584665A');
        $this->addSql('ALTER TABLE product_search DROP FOREIGN KEY FK_D68C9A031DA4AD70');
        $this->addSql('ALTER TABLE product_search DROP FOREIGN KEY FK_D68C9A0312469DE2');
        $this->addSql('ALTER TABLE product_search DROP FOREIGN KEY FK_D68C9A0338248176');
        $this->addSql('ALTER TABLE product_search DROP FOREIGN KEY FK_D68C9A03E4873418');
        $this->addSql('ALTER TABLE product_sub_attribute DROP FOREIGN KEY FK_329AB5B7B6E62EFA');
        $this->addSql('ALTER TABLE product_sub_attribute_translations DROP FOREIGN KEY FK_FD7FA36F2C2AC5D3');
        $this->addSql('ALTER TABLE product_sub_attribute_translations DROP FOREIGN KEY FK_FD7FA36F82F1BAF4');
        $this->addSql('ALTER TABLE product_translations DROP FOREIGN KEY FK_4B13F8EC2C2AC5D3');
        $this->addSql('ALTER TABLE product_translations DROP FOREIGN KEY FK_4B13F8EC82F1BAF4');
        $this->addSql('ALTER TABLE product_variant DROP FOREIGN KEY FK_209AA41D4584665A');
        $this->addSql('ALTER TABLE product_variant_option DROP FOREIGN KEY FK_1CB5D94A3B69A9AF');
        $this->addSql('ALTER TABLE product_variant_option DROP FOREIGN KEY FK_1CB5D94A3DA5256D');
        $this->addSql('ALTER TABLE product_variant_option_translations DROP FOREIGN KEY FK_C965F3792C2AC5D3');
        $this->addSql('ALTER TABLE product_variant_option_translations DROP FOREIGN KEY FK_C965F37982F1BAF4');
        $this->addSql('ALTER TABLE product_variant_translations DROP FOREIGN KEY FK_60D25BED2C2AC5D3');
        $this->addSql('ALTER TABLE product_variant_translations DROP FOREIGN KEY FK_60D25BED82F1BAF4');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE4B89032C');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE97E3DD86');
        $this->addSql('ALTER TABLE project_product DROP FOREIGN KEY FK_455408C8166D1F9C');
        $this->addSql('ALTER TABLE project_product DROP FOREIGN KEY FK_455408C84584665A');
        $this->addSql('ALTER TABLE project_translations DROP FOREIGN KEY FK_EC103EE42C2AC5D3');
        $this->addSql('ALTER TABLE project_translations DROP FOREIGN KEY FK_EC103EE482F1BAF4');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE seo DROP FOREIGN KEY FK_6C71EC30AB839C52');
        $this->addSql('ALTER TABLE seo_seo_social DROP FOREIGN KEY FK_F296CD9297E3DD86');
        $this->addSql('ALTER TABLE seo_seo_social DROP FOREIGN KEY FK_F296CD922A6ABD62');
        $this->addSql('ALTER TABLE seo_page DROP FOREIGN KEY FK_E8DCA6F197E3DD86');
        $this->addSql('ALTER TABLE seo_page_translations DROP FOREIGN KEY FK_ED5F1E392C2AC5D3');
        $this->addSql('ALTER TABLE seo_page_translations DROP FOREIGN KEY FK_ED5F1E3982F1BAF4');
        $this->addSql('ALTER TABLE seo_social_translations DROP FOREIGN KEY FK_4DC1EE9B2C2AC5D3');
        $this->addSql('ALTER TABLE seo_social_translations DROP FOREIGN KEY FK_4DC1EE9B82F1BAF4');
        $this->addSql('ALTER TABLE seo_translations DROP FOREIGN KEY FK_227D72A52C2AC5D3');
        $this->addSql('ALTER TABLE seo_translations DROP FOREIGN KEY FK_227D72A582F1BAF4');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD24B89032C');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD297E3DD86');
        $this->addSql('ALTER TABLE service_translations DROP FOREIGN KEY FK_191BAF622C2AC5D3');
        $this->addSql('ALTER TABLE service_translations DROP FOREIGN KEY FK_191BAF6282F1BAF4');
        $this->addSql('ALTER TABLE shipping_address DROP FOREIGN KEY FK_EB066945A76ED395');
        $this->addSql('ALTER TABLE shipping_address DROP FOREIGN KEY FK_EB0669459F2C3FAB');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F3DA5256D');
        $this->addSql('ALTER TABLE team_translations DROP FOREIGN KEY FK_CE31D7452C2AC5D3');
        $this->addSql('ALTER TABLE team_translations DROP FOREIGN KEY FK_CE31D74582F1BAF4');
        $this->addSql('ALTER TABLE testimonial_translations DROP FOREIGN KEY FK_9BE970A92C2AC5D3');
        $this->addSql('ALTER TABLE testimonial_translations DROP FOREIGN KEY FK_9BE970A982F1BAF4');
        $this->addSql('DROP TABLE banner');
        $this->addSql('DROP TABLE banner_translations');
        $this->addSql('DROP TABLE blog');
        $this->addSql('DROP TABLE blog_blog_tag');
        $this->addSql('DROP TABLE blog_category');
        $this->addSql('DROP TABLE blog_category_translations');
        $this->addSql('DROP TABLE blog_tag');
        $this->addSql('DROP TABLE blog_tag_translations');
        $this->addSql('DROP TABLE blog_translations');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE cart_guest_data');
        $this->addSql('DROP TABLE cart_has_cookie');
        $this->addSql('DROP TABLE cart_has_product_price');
        $this->addSql('DROP TABLE cart_has_user');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE category_translations');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE collection');
        $this->addSql('DROP TABLE collection_translations');
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE coupon_has_product');
        $this->addSql('DROP TABLE credit_card');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE currency_translation');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE dynamic_content');
        $this->addSql('DROP TABLE dynamic_content_attribute');
        $this->addSql('DROP TABLE dynamic_content_attribute_image');
        $this->addSql('DROP TABLE dynamic_content_attribute_document');
        $this->addSql('DROP TABLE dynamic_content_attribute_translations');
        $this->addSql('DROP TABLE dynamic_page');
        $this->addSql('DROP TABLE dynamic_page_translations');
        $this->addSql('DROP TABLE exchange_rate');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE faq_translations');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE image_setting');
        $this->addSql('DROP TABLE image_setting_has_type');
        $this->addSql('DROP TABLE image_type');
        $this->addSql('DROP TABLE language');

        $this->addSql('DROP TABLE occasion');
        $this->addSql('DROP TABLE occasion_translations');
        $this->addSql('DROP TABLE `order`');
        $this->addSql('DROP TABLE order_comment');
        $this->addSql('DROP TABLE order_guest_data');
        $this->addSql('DROP TABLE order_has_coupon');
        $this->addSql('DROP TABLE order_has_product_price');
        $this->addSql('DROP TABLE order_log');
        $this->addSql('DROP TABLE order_shipping_address');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payment_method');
        $this->addSql('DROP TABLE payment_method_translations');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE post_image');
        $this->addSql('DROP TABLE post_translations');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_attribute');
        $this->addSql('DROP TABLE product_attribute_translations');
        $this->addSql('DROP TABLE product_collection');
        $this->addSql('DROP TABLE product_details');
        $this->addSql('DROP TABLE product_has_related_product');
        $this->addSql('DROP TABLE product_favorite');
        $this->addSql('DROP TABLE product_has_attribute');
        $this->addSql('DROP TABLE product_occasion');
        $this->addSql('DROP TABLE product_price');
        $this->addSql('DROP TABLE product_price_has_variant_option');
        $this->addSql('DROP TABLE product_search');
        $this->addSql('DROP TABLE product_sub_attribute');
        $this->addSql('DROP TABLE product_sub_attribute_translations');
        $this->addSql('DROP TABLE product_translations');
        $this->addSql('DROP TABLE product_variant');
        $this->addSql('DROP TABLE product_variant_option');
        $this->addSql('DROP TABLE product_variant_option_translations');
        $this->addSql('DROP TABLE product_variant_translations');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_product');
        $this->addSql('DROP TABLE project_translations');
        $this->addSql('DROP TABLE redirect_404');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE search_keyword');
        $this->addSql('DROP TABLE seo');
        $this->addSql('DROP TABLE seo_seo_social');
        $this->addSql('DROP TABLE seo_base_route');
        $this->addSql('DROP TABLE seo_page');
        $this->addSql('DROP TABLE seo_page_translations');
        $this->addSql('DROP TABLE seo_social');
        $this->addSql('DROP TABLE seo_social_translations');
        $this->addSql('DROP TABLE seo_translations');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_translations');
        $this->addSql('DROP TABLE shipping_address');
        $this->addSql('DROP TABLE site_setting');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_translations');
        $this->addSql('DROP TABLE testimonial');
        $this->addSql('DROP TABLE testimonial_translations');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
