services:
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  App\CMSBundle\Form\:
    resource: '../../Form/*'

  App\CMSBundle\Service\:
    resource: '../../Service/*'

  App\CMSBundle\Twig\:
    resource: '../../Twig/*'

  App\CMSBundle\Controller\Administration\:
    resource: '../../Controller/Administration'
    tags: [ 'controller.service_arguments' ]

  App\CMSBundle\Controller\FrontEnd\:
    resource: '../../Controller/FrontEnd'
    tags: [ 'controller.service_arguments' ]

  App\CMSBundle\Repository\:
    resource: '../../Repository/*'
    tags: [ 'doctrine.repository_service' ]