<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    PN\ServiceBundle\PNServiceBundle::class => ['all' => true],
    PN\MediaBundle\PNMediaBundle::class => ['all' => true],
    PN\LocaleBundle\PNLocaleBundle::class => ['all' => true],
    PN\ContentBundle\PNContentBundle::class => ['all' => true],
    PN\SeoBundle\PNSeoBundle::class => ['all' => true],
    App\ContentBundle\ContentBundle::class => ['all' => true],
    App\SeoBundle\SeoBundle::class => ['all' => true],
    App\MediaBundle\MediaBundle::class => ['all' => true],
    App\BaseBundle\BaseBundle::class => ['all' => true],
    App\CMSBundle\CMSBundle::class => ['all' => true],
    App\UserBundle\UserBundle::class => ['all' => true],
    App\HomeBundle\HomeBundle::class => ['all' => true],
    App\ProductBundle\ProductBundle::class => ['all' => true],
    App\CurrencyBundle\CurrencyBundle::class => ['all' => true],
    App\ECommerceBundle\ECommerceBundle::class => ['all' => true],
    App\OnlinePaymentBundle\OnlinePaymentBundle::class => ['all' => true],
    App\CustomBundle\CustomBundle::class => ['all' => true],
    App\ShippingBundle\ShippingBundle::class => ['all' => true],
    App\ReportBundle\ReportBundle::class => ['all' => true],
    App\VendorBundle\VendorBundle::class => ['all' => true],
    App\NewShippingBundle\NewShippingBundle::class => ['all' => true],
    App\ThreeSixtyViewBundle\ThreeSixtyViewBundle::class => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    KnpU\OAuth2ClientBundle\KnpUOAuth2ClientBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
];
