<?php

namespace App\CMSBundle\Repository;

use App\BaseBundle\Repository\BaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;
use App\CMSBundle\Entity\Project;
use PN\ServiceBundle\Utils\Validate;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends BaseRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Project::class, "p");
    }


    protected function getStatement(): QueryBuilder
    {
        return $this->createQueryBuilder('p')
            ->addSelect("p.tarteb AS HIDDEN inverseTarteb")
            ->addSelect("seo")
            ->addSelect("seoTrans")
            ->addSelect("post")
            ->leftJoin("p.seo", "seo")
            ->leftJoin("seo.translations", "seoTrans")
            ->leftJoin("p.post", "post");
    }

    private function filterOrder(QueryBuilder $statement, \stdClass $search): void
    {
        $sortSQL = [
            'p.id',
            'inverseTarteb',
            'p.title',
            'p.publish',
            'p.featured',
            'p.created',
        ];

        $this->filterOrderLogic($statement, $search, $sortSQL);
    }

    private function filterWhereClause(QueryBuilder $statement, \stdClass $search): void
    {
        if (isset($search->string) and Validate::not_null($search->string)) {
            $statement->andWhere('p.id LIKE :searchTerm '
                .'OR p.title LIKE :searchTerm '
            );
            $statement->setParameter('searchTerm', '%'.trim($search->string).'%');
        }

        if (isset($search->ids) and is_array($search->ids) and count($search->ids) > 0) {
            $statement->andWhere('p.id in (:ids)');
            $statement->setParameter('ids', $search->ids);
        }

        if (isset($search->publish) and $search->publish != "") {
            $statement->andWhere('p.publish = :publish');
            $statement->setParameter('publish', $search->publish);
        }

        if (isset($search->featured) and $search->featured != "") {
            $statement->andWhere('p.featured = :featured');
            $statement->setParameter('featured', $search->featured);
        }

        if (isset($search->deleted) and in_array($search->deleted, [0, 1])) {
            if ($search->deleted == 1) {
                $statement->andWhere('p.deleted IS NOT NULL');
            } else {
                $statement->andWhere('p.deleted IS NULL');
            }
        }
    }

    public function filter($search, $count = false, $startLimit = null, $endLimit = null)
    {
        $statement = $this->getStatement();
        $this->filterWhereClause($statement, $search);

        if ($count) {
            return $this->filterCount($statement);
        }

        $statement->groupBy('p.id');
        $this->filterPagination($statement, $startLimit, $endLimit);
        $this->filterOrder($statement, $search);

        return $statement->getQuery()->execute();
    }
}
