<?php

namespace App\CMSBundle\Repository;

use App\BaseBundle\Repository\BaseRepository;
use Doctrine\Persistence\ManagerRegistry;
use App\CMSBundle\Entity\Team;
use PN\ServiceBundle\Utils\SQL;
use PN\ServiceBundle\Utils\Validate;

/**
 * MangmentTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends BaseRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Team::class);
    }

    public function filter($search, $count = false, $startLimit = null, $endLimit = null)
    {

        $sortSQL = [
            't.tarteb',
            't.name',
            't.publish',
        ];

        $connection = $this->getEntityManager()->getConnection();
        $where = false;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) and !is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }

        if (isset($searchFiltered->publish) and in_array($searchFiltered->publish, [0, 1])) {
            $where = ($where) ? " AND " : " WHERE ";
            $clause .= $where." t.publish = $searchFiltered->publish ";
        }

        if (isset($searchFiltered->deleted) and in_array($searchFiltered->deleted, [0, 1])) {
            $where = ($where) ? " AND " : " WHERE ";
            if ($searchFiltered->deleted == 1) {
                $clause .= $where." t.deleted IS NOT NULL ";
            } else {
                $clause .= $where." t.deleted IS NULL ";
            }
        }

        if (isset($searchFiltered->string) and $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 't.id', $where);
                $clause .= SQL::searchSCG($searchFiltered->string, 't.name', ' OR ');
                $clause .= SQL::searchSCG($searchFiltered->string, 't.position', ' OR ');
                $clause .= SQL::searchSCG($searchFiltered->string, 't.companyName', ' OR ');
                $clause .= " ) ";
            }
        }


        if ($count) {
            $sqlInner = 'SELECT COUNT(t.id) AS `count` FROM team t ';
            $sqlInner .= $clause;

            $statement = $connection->prepare($sqlInner);

            return $statement->executeQuery()->fetchOne();
        }

        $sql = 'SELECT t.id FROM team t ';
        $sql .= $clause;
        if (isset($searchFiltered->ordr) and Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) and array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER by ".$sortSQL[$columnNumber]." $dir";
            }
        } else {
            $sql .= ' ORDER by t.id DESC';
        }

        if ($startLimit !== null and $endLimit !== null) {
            $sql .= " LIMIT ".$startLimit.", ".$endLimit;
        }
        $statement = $connection->prepare($sql);
        $filterResult = $statement->executeQuery()->fetchAllAssociative();
        $result = [];

        foreach ($filterResult as $key => $r) {
            $result[] = $this->find($r['id']);
        }

        return $result;
    }

}
