services:
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: true

  App\NewShippingBundle\Form\:
    resource: '../../Form/*'
    public: false

  App\NewShippingBundle\EventListener\:
    resource: '../../EventListener/*'
    public: false

  App\NewShippingBundle\EventListener\ShippingZonePriceSpecificWeightListener:
    tags:
      - { name: 'doctrine.event_subscriber' }

  App\NewShippingBundle\Repository\:
    resource: '../../Repository/*'
    tags: [ 'doctrine.repository_service' ]

  App\NewShippingBundle\Service\:
    resource: '../../Service/*'
