<?php

namespace App\ProductBundle\Repository;

use App\BaseBundle\Repository\BaseRepository;
use App\MediaBundle\Entity\Image;
use App\ProductBundle\Entity\Product;
use App\UserBundle\Entity\User;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;
use PN\ServiceBundle\Utils\Validate;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Product::class, "p");
    }

    public function find($id, $lockMode = null, $lockVersion = null): ?object
    {
        $statement = $this->getStatement();
        $statement->where("p.id=:id");
        $statement->setParameter("id", $id);
        //        if ($product) {
        //            $product->minPrice = $this->getEntityManager()->getRepository(ProductPrice::class)->getMinPriceByProduct($product);
        //        }
        return $statement->getQuery()->getOneOrNullResult();
    }

    /**
     * use in admin panel
     * @param Product $currentProduct
     * @return Product|null
     * @throws NonUniqueResultException
     */
    public function getNextProductByCurrentProduct(Product $currentProduct): ?Product
    {
        $statement = $this->createQueryBuilder('p')
            ->where("p.deleted IS NULL")
            ->andWhere("p.id > :currentProductId")
            ->setParameter("currentProductId", $currentProduct->getId())
            ->orderBy("p.id", "ASC")
            ->setMaxResults(1);

        return $statement->getQuery()->getOneOrNullResult();

    }

    /**
     * use in admin panel
     * @param Product $currentProduct
     * @return Product|null
     * @throws NonUniqueResultException
     */
    public function getPreviousProductByCurrentProduct(Product $currentProduct): ?Product
    {
        $statement = $this->createQueryBuilder('p')
            ->where("p.deleted IS NULL")
            ->andWhere("p.id < :currentProductId")
            ->setParameter("currentProductId", $currentProduct->getId())
            ->orderBy("p.id", "DESC")
            ->setMaxResults(1);

        return $statement->getQuery()->getOneOrNullResult();
    }


    public function getRelatedProduct(Product $product, User $user = null, $limit = 3): array
    {
        $search = new \stdClass();
        $search->notEqualProduct = $product->getId();
        $search->category = $product->getCategory()->getId();
        $search->deleted = 0;
        $search->publish = 1;
        if ($user) {
            $search->currentUserId = $user->getId();
        }

        return $this->filter($search, false, 0, $limit);
    }

    public function makeImageEmptyByImage(Image $image)
    {
        return $this->createQueryBuilder("p")
            ->update()
            ->set("p.mainImage", "null")
            ->where("p.mainImage = :id")
            ->setParameter("id", $image->getId())
            ->getQuery()
            ->execute();
    }

    protected function getStatement(\stdClass $search = null): QueryBuilder
    {
        $statement = $this->createQueryBuilder('p')
            ->addSelect("pd")
            ->addSelect("c")
            ->addSelect("pTrans")
            ->addSelect("post")
            ->addSelect("postTrans")
            ->addSelect("seo")
            ->addSelect("seoTrans")
            ->addSelect("cTrans")
            ->addSelect("cTransLang")
            ->addSelect("sa")
            ->addSelect("v")
            ->leftJoin('p.category', 'c')
            ->leftJoin('p.details', 'pd')
            ->leftJoin("p.translations", "pTrans")
            ->leftJoin('p.post', 'post')
            ->leftJoin('post.translations', 'postTrans')
            ->leftJoin("p.seo", "seo")
            ->leftJoin("seo.translations", "seoTrans")
            ->leftJoin("c.translations", "cTrans")
            ->leftJoin("cTrans.language", "cTransLang")
            ->leftJoin("p.storeAddress", "sa")
            ->leftJoin("sa.vendor", "v");


        if (isset($search->currentCollectionId) and Validate::not_null($search->currentCollectionId)) {
            $statement->leftJoin('p.productHasCollections', 'pc', "WITH", "pc.collection=:currentCollectionId");
            $statement->addSelect("IDENTITY(pc.product) selectedProductInCollection");
            $statement->setParameter("currentCollectionId", $search->currentCollectionId);
        } else {
            $statement->addSelect("pc");
            $statement->leftJoin('p.productHasCollections', 'pc');
        }
        if (isset($search->currentOccasionId) and Validate::not_null($search->currentOccasionId)) {
            $statement->leftJoin('p.productHasOccasions', 'oca', "WITH", "oca.occasion=:currentOccasionId");
            $statement->addSelect("IDENTITY(oca.product) selectedProductInOccasion");
            $statement->setParameter("currentOccasionId", $search->currentOccasionId);
        } else {
            $statement->leftJoin('p.productHasOccasions', 'oca');
        }

        if (isset($search->currentCouponId) and Validate::not_null($search->currentCouponId)) {
            $statement->leftJoin('p.couponHasProducts', 'pco', "WITH", "pco.coupon=:currentCouponId");
            $statement->addSelect("IDENTITY(pco.product) selectedProductInCoupon");
            $statement->setParameter("currentCouponId", $search->currentCouponId);
        } else {
            $statement->leftJoin('p.couponHasProducts', 'pco');
        }

        return $statement;
    }

    private function filterWhereClause(QueryBuilder $statement, \stdClass $search)
    {
        if (isset($search->string) and Validate::not_null($search->string)) {
            $statement->andWhere('p.id LIKE :searchTerm '
                . 'OR p.title LIKE :searchTerm '
                . 'OR p.sku LIKE :searchTerm '
            );
            $statement->setParameter('searchTerm', '%' . trim($search->string) . '%');
        }
        if (isset($search->notEqualProduct) and $search->notEqualProduct != "") {
            $statement->andWhere('p.id != :notEqualProduct');
            $statement->setParameter('notEqualProduct', $search->notEqualProduct);
        }

        if (isset($search->uuid) and $search->uuid != "") {
            $statement->andWhere('p.uuid = :uuid');
            $statement->setParameter('uuid', $search->uuid);
        }


        if (isset($search->publish) and (is_bool($search->publish) or in_array($search->publish, [0, 1]))) {
            $statement->andWhere('p.publish = :publish');
            $statement->setParameter('publish', $search->publish);
        }

        if (isset($search->featured) and (is_bool($search->featured) or in_array($search->featured, [0, 1]))) {
            $statement->andWhere('p.featured = :featured');
            $statement->setParameter('featured', $search->featured);
        }
        if (isset($search->newArrival) and (is_bool($search->newArrival) or in_array($search->newArrival, [0, 1]))) {
            $statement->andWhere('p.newArrival = :newArrival');
            $statement->setParameter('newArrival', $search->newArrival);
        }


        if (isset($search->collection) and $search->collection != "") {
            $statement->andWhere('pc.collection = :collection');
            $statement->setParameter('collection', $search->collection);
        }

        if (isset($search->occasion) and $search->occasion != "") {
            $statement->andWhere('oca.occasion = :occasion');
            $statement->setParameter('occasion', $search->occasion);
        }

        if (isset($search->availability) and $search->availability == "in-stock") {
            $statement->andWhere('pd.stock > 0');
        } elseif (isset($search->availability) and $search->availability == "out-stock") {
            $statement->andWhere('pd.stock <= 0');
        }

        if (isset($search->category) and $search->category != "") {
            $statement->andWhere('p.category = :category');
            $statement->setParameter('category', $search->category);
        }

        if (isset($search->categories) and is_array($search->categories) and count($search->categories) > 0) {
            $statement->andWhere('p.category IN (:categories)');
            $statement->setParameter('categories', $search->categories);
        }

        if (isset($search->vendor) and $search->vendor != "") {
            $statement->andWhere('p.vendor = :vendor');
            $statement->setParameter('vendor', $search->vendor);
        }

        if (isset($search->vendors) and is_array($search->vendors) and count($search->vendors) > 0) {
            $statement->andWhere('p.vendor IN (:vendors)');
            $statement->setParameter('vendors', $search->vendors);
        }


        if (isset($search->ids) and is_array($search->ids) and count($search->ids) > 0) {
            $statement->andWhere('p.id IN (:ids)');
            $statement->setParameter('ids', $search->ids);
        }

        if (isset($search->notId) and $search->notId != "") {
            $statement->andWhere('p.id <> :notId');
            $statement->setParameter('notId', $search->notId);
        }

        if (isset($search->uuids) and is_array($search->uuids) and count($search->uuids) > 0) {
            $statement->andWhere('p.uuid IN (:uuids)');
            $statement->setParameter('uuids', $search->uuids);
        }

        if (isset($search->deleted) and in_array($search->deleted, [0, 1])) {
            if ($search->deleted == 1) {
                $statement->andWhere('p.deleted IS NOT NULL');
            } else {
                $statement->andWhere('p.deleted IS NULL');
            }
        }
    }

    private function filterOrder(QueryBuilder $statement, \stdClass $search): void
    {
        $sortSQL = [
            'p.id',
            'p.sku',
            'p.title',
            'p.id',
            'c.title',
            'v.title',
            "p.created", // Recently added
            'p.publish',
            "RAND()", // Recently added
        ];

        if (isset($search->currentCollectionId) and Validate::not_null($search->currentCollectionId)) {
            array_unshift($sortSQL, "selectedProductInCollection");
        }
        if (isset($search->currentOccasionId) and Validate::not_null($search->currentOccasionId)) {
            array_unshift($sortSQL, "selectedProductInOccasion");
        }
        if (isset($search->currentCouponId) and Validate::not_null($search->currentCouponId)) {
            array_unshift($sortSQL, "selectedProductInCoupon");
        }
        $this->filterOrderLogic($statement, $search, $sortSQL);
        $statement->addOrderBy("p.title", "ASC");
    }

    public function filter($search, $count = false, $startLimit = null, $endLimit = null): array|int
    {
        $statement = $this->getStatement($search);
        $this->filterWhereClause($statement, $search);

        if ($count) {
            return $this->filterCount($statement);
        }

        $statement->groupBy('p.id');
        $this->filterPagination($statement, $startLimit, $endLimit);
        $this->filterOrder($statement, $search);
        $rows = $statement->getQuery()->execute();
        $entities = [];
        foreach ($rows as $row) {
            if (is_array($row)) {
                $product = $row[0];
                $product->inCollection = (array_key_exists("selectedProductInCollection",
                        $row) and $row['selectedProductInCollection'] != null);
                $product->inOccasion = (array_key_exists("selectedProductInOccasion", $row) and $row['selectedProductInOccasion'] != null);
                $product->inCoupon = (array_key_exists("selectedProductInCoupon", $row) and $row['selectedProductInCoupon'] != null);
            } else {
                $product = $row;
            }
            $entities[] = $product;
        }

        return $entities;
    }

    public function getProductByImage(Image $image): ?Product
    {
        return $this->createQueryBuilder("p")
            ->leftJoin("p.post", "po")
            ->leftJoin("po.images", "i")
            ->andWhere("i.id = :id")
            ->setParameter("id", $image->getId())
            ->getQuery()
            ->getOneOrNullResult();

    }

    public function isValidToShowInFrontEnd(Product $product): bool
    {
        $statement = $this->createQueryBuilder("p")
            ->select("p.publish AS productId")
            ->andWhere("p.publish = 1")
            ->andWhere("p.deleted IS NULL")
            ->andWhere("p.id = :productId")
            ->setParameter("productId", $product);
        $result = $statement->getQuery()->getOneOrNullResult();
        if ($result === null) {
            return false;
        }

        return true;
    }

    private function getMinimumProductPrice(Product $product): ?float
    {
        $prices = $product->getPrices();
        $minPrice = PHP_INT_MAX;
        if (!empty($prices)) {
            foreach ($prices as $price) {
                if ($price->getSellPrice() < $minPrice) {
                    $minPrice = $price->getSellPrice();
                }
            }
        }

        return $minPrice;
    }

    private function getMaximumProductPrice(Product $product): ?float
    {
        $prices = $product->getPrices();
        $maxPrice = 0;
        if (!empty($prices)) {
            foreach ($prices as $price) {
                if ($price->getSellPrice() > $maxPrice) {
                    $maxPrice = $price->getSellPrice();
                }
            }
        }

        return $maxPrice;
    }


}
