<?php

namespace App\ProductBundle\Repository;

use App\BaseBundle\Repository\BaseRepository;
use App\ProductBundle\Entity\Attribute;
use Doctrine\Persistence\ManagerRegistry;
use App\ProductBundle\Entity\SearchKeyword;
use PN\ServiceBundle\Utils\IPService;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchKeywordsRepository extends BaseRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, SearchKeyword::class, "sk");
    }

    private function canonicalizeKeyword($keyword)
    {
        $keyword = trim($keyword);
        $keyword = strtolower($keyword);
        $keyword = preg_replace('/\s+/', '-', $keyword);

        return strtolower($keyword);
    }

    public function insert($keyword)
    {
        $keyword = trim($keyword);
        $canonicalKeyword = $this->canonicalizeKeyword($keyword);
        $ip = IPService::getIp();
        $searchKeyword = $this->findOneBy(['canonicalKeyword' => $canonicalKeyword, "ip" => $ip]);
        if (!$searchKeyword) {
            $searchKeyword = new SearchKeyword();
            $searchKeyword->setKeyword($keyword);
            $searchKeyword->setCanonicalKeyword($canonicalKeyword);
            $searchKeyword->setIp($ip);
        }

        $em = $this->getEntityManager();
        $em->persist($searchKeyword);
        $em->flush();
    }

    public function topSearchKeywords($limit = 10)
    {
        $statement = $this->createQueryBuilder("s")
            ->select("sk.keyword, COUNT(sk.canonicalKeyword) countKeywords")
            ->orderBy("countKeywords", "DESC")
            ->groupBy("sk.canonicalKeyword")
            ->setMaxResults($limit);

        return $statement->getQuery()->getResult();
    }
}
